# Generated by Django 3.1.7 on 2021-03-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0002_location_lat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
