# Generated by Django 3.1.7 on 2021-04-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0004_auto_20210329_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='hotel',
        ),
        migrations.AddField(
            model_name='schedule',
            name='hotel',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='schedule',
            name='transportation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
