# Generated by Django 3.2.3 on 2021-05-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0006_schedule_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='schedule',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
