# Generated by Django 3.2.3 on 2021-05-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0007_auto_20210525_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='schedule_id',
            field=models.IntegerField(default=0),
        ),
    ]
