# Generated by Django 3.2.3 on 2021-05-25 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0008_review_schedule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='schedule_id',
        ),
        migrations.AddField(
            model_name='review',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itinerary.schedule'),
            preserve_default=False,
        ),
    ]
